### ISSUE TITLE
Increase Keylength for the apache Certificate

### ISSUE THREAD

**Issue by Alucard616** [Katello/katello-certs-tools#2]
When using just the foreman-installer, the keylength will be set at 4096 Bit.
But with Katello the Keylength will be set at 2048 Bit.

I think it would be nice, changing the Keylength from 2048 Bit to 4096 Bit

**Comment by ekohl** [comment]
Fixed in 19f94aeac89c7b4e5264ac2e8dc085ecd4feba60 and released as 2.7.0.
